### PR TITLE
Add table of contents

### PR DESCRIPTION
**Pull request by jameskolce**

### CODE REVIEW

**Comment by jedireza** [comment]
Awesome! Thanks for creating an PR. A couple things:

 - Let's move the install section under the table of contents and make a bullet item for it above usage.
 - The Model API > Properties > `_idClass` link isn't working. There is a misspelling in the anchor.

**Comment by jameskolce** [comment]
Done!

**Comment by jedireza** [comment]
Great. Let's squash the commits into one `added table of contents` and we'll be good to go.

**Comment by jameskolce** [comment]
Done, I squashed the latest commits into the first one.

**Comment by jedireza** [comment]
Thanks!

**Comment by jameskolce** [comment]
You're welcome!

**Pull request merged**
