### PR TITLE
fixed package.json to allow tests to run on Windows

### PR DESCRIPTION
**Pull request by simon-p-r**
Enables running lab on Windows, also added test coverage script for windows in separate script.

### CODE REVIEW

**Comment by jedireza** [comment]
Thanks for creating a PR.

The changes are mostly reasonable. I don't like the new script just for Windows though. Maybe we can try using the [`open`](https://www.npmjs.com/package/open) module instead.

**Comment by simon-p-r** [comment]
Ok we could wrap the open module in a script that gets called from package or we see if  [open](https://www.npmjs.com/package/open) will implement a command line interface.  I willing to help either way!

**Comment by jedireza** [comment]
Ah good point about the cli. I found an alternative! [`opn-cli`](https://www.npmjs.com/package/opn-cli). We should add this to `devDependencies` and change `open` to `opn` and it should work. Give it a shot, if it works on Windows, update this PR and we :shipit:.

**Comment by jedireza** [comment]
Great. I just tested on my mac and it's working.

Would you please:

 - change the version from `"opn-cli": "^1.0.0",` to match the others like `"opn-cli": "^1.x.x",`
 - squash the commits into one

Then I'll do a merge and a release.

**Comment by jedireza** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by simon-p-r** [comment]
Thanks my first rebase and I think it is all ok now!

**Comment by jedireza** [comment]
Great job! Thanks for contributing! :cake:

**Pull request merged**
